# -- Theme Options --
colorScheme = "blowfish"
defaultAppearance = "dark"
autoSwitchAppearance = true
enableA11y = false
enableSearch = true
enableCodeCopy = true
replyByEmail = false
disableImageOptimization = false
disableImageOptimizationMD = false
disableTextInHeader = false
highlightCurrentMenuArea = true
fingerprintAlgorithm = "sha512"
colorScheme = "blowfish"
defaultAppearance = "dark"

[seo]
  # metaDescriptionOrder = ["summary", "description", "site"]

[header]
  layout = "fixed"
  # mobileMenuStyle = "fullscreen"

[footer]
  showMenu = true
  showCopyright = true
  showThemeAttribution = false
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]
  layout = "hero"
  # homepageImage = "IMAGE.jpg"
  showRecent = true
  showRecentItems = 6
  showMoreLink = true
  showMoreLinkDest = "/posts/"
  cardView = false

[article]
  showDate = true
  showViews = false
  showLikes = false
  showDateOnlyInArticle = false
  showDateUpdated = true
  showAuthor = true
  showHero = false
  showBreadcrumbs = false
  showDraftLabel = true
  showEdit = false
  showHeadingAnchors = true
  showPagination = true
  invertPagination = false
  showReadingTime = true
  showReadingProgress = false
  showTableOfContents = true
  showRelatedContent = true
  relatedContentLimit = 3
  showTaxonomies = true
  showCategories = true
  showTags = true
  showWordCount = true
  sharingLinks = ["linkedin", "email"]
  showZenMode = false

[list]
  showHero = false
  showBreadcrumbs = false
  showSummary = true
  showTableOfContents = false
  showCards = false
  orderByWeight = false
  groupByYear = true
  cardView = false
  constrainItemsWidth = false

[taxonomy]
  showTermCount = true
  showHero = false
  showBreadcrumbs = false
  showTableOfContents = false
  cardView = false

[term]
  showHero = false
  showBreadcrumbs = false
  showTableOfContents = true
  groupByYear = false
  cardView = false

[sitemap]
  excludedKinds = ["taxonomy", "term"]
